[project]
name = "BetterOdooApiWrapper"
version = "0.1.1"
description = "A minimal Python ORM wrapper for the Odoo API."
readme = "README.md"
authors = [
    {name = "Kyan Machiels", email = "kyan.machiels@e-powerinternational.com"},
    {name = "Bert Proesmans", email = "bert.proesmans@e-powerinternational.com"}
]
dependencies = []
requires-python = ">=3.5"
license = {text = "MIT"}

[project.urls]
homepage = "https://github.com/europowergenerators/BetterOdooApiWrapper"
Documentation = "https://github.com/europowergenerators/BetterOdooApiWrapper"
"Issue tracker" = "https://github.com/europowergenerators/BetterOdooApiWrapper/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["BetterOdooApiWrapper"]
